version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "5001:8080"
  main-service:
    build: ./main-service
    ports:
      - "5002:8080"
  task-service:
    build: ./task-service
    ports:
      - "5003:8080"