version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: nore_task_auth
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: rahasia123
      MYSQL_PASSWORD: rahasia123
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    build: .
    container_name: auth-service
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "5001:5001"
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge